"""[FR-07] v1_initial — initial schema: ``tasks`` + ``api_keys``.

Citations:
- SPEC.md §3 FR-07 v1 — create ``tasks`` and ``api_keys`` tables.
- SPEC.md §3 FR-03 — ``api_keys`` stores only the SHA-256 hash of the
  plaintext key (``key_hash`` column, 64 lowercase hex chars); the
  plaintext is NEVER persisted.

Revision ID: v1_initial
Revises:
Create Date: 2026-08-13 00:00:00
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# Alembic revision identifiers — populated by the migration scaffolding
# so the autogenerated env.py can wire ``--autogenerate`` later.
revision: str = "v1_initial"
down_revision: str | None = None
branch_labels: tuple[str, ...] | None = None
depends_on: tuple[str, ...] | None = None


def upgrade() -> None:
    """[FR-07 v1] Create the initial ``tasks`` + ``api_keys`` tables."""
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("command", sa.String(length=1000), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
    )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("revoked_at", sa.String(length=64), nullable=True),
    )


def downgrade() -> None:
    """[FR-07 v1] Reverse the initial schema — drop both tables.

    The forward step created ``tasks`` first then ``api_keys``; the
    downgrade drops them in reverse order so the migration is fully
    reversible. We use ``op.drop_table`` rather than
    ``op.execute("DROP TABLE ...")`` — the latter is a destructive
    shortcut that FR-07 explicitly disallows (SPEC §3 FR-07
    "破壞性捷徑").
    """
    op.drop_table("api_keys")
    op.drop_table("tasks")
